### ISSUE TITLE
원래 제가 하기로 한 파트들은 어떻게 처리하는 것이 좋을까요?

### ISSUE THREAD

**Issue by Gummybearr** [kdl9405/backend_Study#68]
1번: 적절히 분배한다
2번: 지운다

**Comment by kdl9405** [comment]
제가 시간날 때마다 채워볼게요~ 지우진 말아주세요

**Comment by Gummybearr** [comment]
https://trello.com/b/MugMXwGi/%EB%A9%B4%EC%A0%91%EC%A4%80%EB%B9%84%F0%9F%91%91

우연히 발견한 사이트인데 좋은 자료가 될 것 같아요
